### ISSUE TITLE
Stops and ShapePoints as Geometries

### ISSUE THREAD

**Issue by russellhoff** [conveyal/gtfs-lib#131]
For the time being, Stops and ShapePoints are stored as Double data typed Latitude and Longitude attributes. 

Would it be possible to add a Geometry (JTS) attribute? It would be nice as sometimes I work with GIS tools. I'd lend a hand to you.

Thanks!

**Comment by landonreed** [comment]
Apologies for the delay, @russellhoff. I think this might be too far afield from gtfs-lib's primary focus. And a [recent comment](https://github.com/conveyal/gtfs-lib/issues/97#issuecomment-446924050) by @abyrd suggests that we would not be looking to leak any JTS objects outside gtfs-lib.

Is this a correct interpretation, @abyrd?

**Comment by abyrd** [comment]
@russellhoff when you say a "Geometry (JTS) attribute" do you mean a field on these classes, or a method that returns a new Geometry (Point) object?

We will almost certainly not change the fields in these classes, as they are intended to closely reflect the structure of GTFS data itself, which has two floating point fields for latitude and longitude. 

It would be possible to add a method that returns a JTS object. But as @landonreed says this is somewhat outside the scope of the library. Couldn't you just make your own static utility method to do this, since the latitude and longitude fields are public?

**Comment by russellhoff** [comment]
Yes @abyrd , you're right. It's nonsense to add a Geometry attribute. Apologies!
