### ISSUE TITLE
Arbitrary 2 hour limit on frequencies#headway_secs

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-lib#148]
I'm not sure that there is any hard upper limit on the `headway_secs` field. Is there a reason we're establishing this to be 2 hours? I realize most frequency service would and should be defined for less than this, but this limit should probably receive an explanatory comment.

https://github.com/conveyal/gtfs-lib/blob/54aff02b5be878bb14a4255a54978e4abc117b38/src/main/java/com/conveyal/gtfs/loader/Table.java#L284

cc @abyrd

**Comment by abyrd** [comment]
I think when I added the range checking I just made up reasonable limits. If you think there might be frequency routes higher than this we can raise it to 4 hours or more. I doubt there's such a thing in pure frequency routes since it implies waiting 0-2 hours for a bus, but I can imagine an exact-times ferry running every 4 hours.

Yes we can always add comments, and we should probably increase this to 4+ hours, so we're only catching cases where people have e.g. exported milliseconds instead of seconds by accident.
