### ISSUE TITLE
Check GTFS fields for new lines and other special characters

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-lib#191]
According to the [GTFS spec](https://developers.google.com/transit/gtfs/reference/#file_requirements),

> Field values may not contain tabs, carriage returns or new lines.

I don't believe we are checking for this anywhere and recently a GTFS feed for Tompkins Consolidated Area Transit (TCAT) passed our validator and ended up choking OpenTripPlanner's OBA GTFS reader.

**Comment by abyrd** [comment]
@landonreed if I remember right there is a need throughout these innermost method calls for a way to report and register errors, which is complicated by the fact that the whole thing is designed to allow loading into a database or into Java objects with the same code. We don't use the code path of loading into Java objects but the original idea was to merge those two code paths, so that our newest and best validators would apply in both situations, and we could get rid of a lot of duplicate code.

I will look at this more closely to suggest a way to report errors.
